// 13、Learn_unipaa_taro/11-api-uni-app/pages/detail02/detail02.vue
<template>
	<view>
		<button type="default" @click="goBack">返回</button>
	</view>
</template>

<script setup>
	import {
		getCurrentInstance,
		ref
	} from 'vue'
 
	const $instance = ref(getCurrentInstance().proxy) // this 
 
	function goBack() {
		uni.navigateBack({
			delta: 1
		})
		const eventChannel = $instance.value.getOpenerEventChannel()
		// 触发事件, 将detail02的数据传递给Home页面
		eventChannel.emit('acceptDataFormDetail02', {
			data: '这里是detail02传递给Home页面的数据'
		})
	}
</script>

<style lang="scss">

</style>

// 13、Learn_unipaa_taro/14-base-taro/src/pages/detail02/index.jsx
import { Component } from "react";
import { View, Button } from "@tarojs/components";
import Taro from "@tarojs/taro";
import "./index.scss";

export default class Detail02 extends Component {
  UNSAFE_componentWillMount() {}

  componentDidMount() {}

  componentWillUnmount() {}

  $intance = Taro.getCurrentInstance(); // 是可以拿到当前的app实例，page实例和router对象

  componentDidShow() {}

  componentDidHide() {}

  goBack() {
    Taro.navigateBack({
      delta: 1,
    });

    if (process.env.TARO_ENV === "weapp") {
      // const pages = Taro.getCurrentPages()
      // const page = pages[pages.length - 1]
      // 注意：这中方式只支持微信小程序端
      const eventChannel = this.$intance.page.getOpenerEventChannel();
      eventChannel.emit("acceptDataFromDetail02Page", {
        data: "拿到detail02传递到home页面的数据",
      });
    }
  }

  render() {
    return (
      <View className="detail02">
        <Button onClick={() => this.goBack()}>返回</Button>
      </View>
    );
  }
}
