// 13、Learn_unipaa_taro/HYMallApp/src/pages/home/cpns/home-banner/index.jsx
import { memo } from "react";
import { Swiper, SwiperItem, Image } from "@tarojs/components";
import PropTypes from "proptypes";
import Taro from "@tarojs/taro";
import styles from "./index.module.scss";

const HomeBanner = memo(function(props) {
  const { banners } = props;
  function handleItemClick(url) {
    if (!url) return;
    Taro.navigateTo({
      url: "/pages/webview/index?link=" + url
    });
  }
  return (
    <Swiper
      className={styles["home-banner"]}
      indicatorDots
      indicatorColor="#999"
      indicatorActiveColor="#ff464e"
      autoplay
      interval={3000}
    >
      {banners.map(item => {
        return (
          <SwiperItem key={item.id}>
            <Image
              className={styles["banner-img"]}
              src={item.pic}
              mode="widthFix"
              onClick={() => handleItemClick(item.jump_url)}
            ></Image>
          </SwiperItem>
        );
      })}
    </Swiper>
  );
});

export default HomeBanner;

HomeBanner.propType = {
  banners: PropTypes.array
};

// 13、Learn_unipaa_taro/13-HYMallApp/pages/home/cpns/home-banner.vue
<template>
  <swiper
    class="banner"
    :indicator-dots="true"
    indicator-active-color="#ff8198"
    :autoplay="true"
    :interval="3000"
    :duration="1000"
  >
    <template v-for="item in banners" :key="item">
      <swiper-item @click="handleItemClick(item)">
        <image class="image" :src="item.image" mode="widthFix"></image>
      </swiper-item>
    </template>
  </swiper>
</template>

<script setup>
const props = defineProps({
  banners: {
    type: Array,
    default: () => []
  }
});
const emit = defineEmits(['bannerItemClick']);
function handleItemClick(item) {
  emit('bannerItemClick', item.link);
}
</script>

<style lang="scss">
// 150 px — 300rpx
.banner {
  .image {
    width: 100%;
  }
}
</style>
