// 13、Learn_unipaa_taro/14-base-taro/src/pages/detail03/index.jsx
import { Component } from "react";
import { View, Button } from "@tarojs/components";
import Taro from "@tarojs/taro";
import "./index.scss";

export default class Detail03 extends Component {
  componentDidMount() {}

  componentWillUnmount() {}

  componentDidShow() {}

  componentDidHide() {}
  goBack() {
    Taro.navigateBack({
      delta: 1,
    });

    // 触发一个全局事件
    Taro.eventCenter.trigger("acceptDataFormDatail03Page", {
      data: "将detail03的数据传递到home页面",
    });
  }
  render() {
    return (
      <View className="detail03">
        <Button onClick={() => this.goBack()}>返回</Button>
      </View>
    );
  }
}

// 13、Learn_unipaa_taro/11-api-uni-app/pages/detail03/detail03.vue
<template>
	<view>
		<button type="default" @click="goBack">返回</button>
	</view>
</template>

<script setup> 

	function goBack() {
		uni.navigateBack({
			delta: 1
		})
		
		// 触发事件( 通过事件总线 )
		uni.$emit('acceptDataFormDetail03', {
			data: '这里的数据是从detail03传递到home页面'
		})
	}
	
</script>

<style lang="scss">

</style>
