// 13、Learn_unipaa_taro/14-base-taro/src/pages/detail04/index.jsx
import { Component } from "react";
import { View } from "@tarojs/components";
import Taro from "@tarojs/taro";
import "./index.scss";

export default class Detail04 extends Component {
  // 1.组件的生命周期（会调用）
  // UNSAFE_componentWillMount() {
  //   console.log("detail04 UNSAFE_componentWillMount");
  // }

  // componentDidMount() {
  //   console.log("detail04 componentDidMount");
  // }

  // componentWillUnmount() {
  //   console.log("detail04 componentWillUnmount");
  // }

  // 2.页面的生命周期
  onLoad() {
    console.log("detail04 onLoad");
  }
  componentDidShow() {
    console.log("detail04 componentDidShow");
  }
  onReady() {
    console.log("detail04 onReady");
  }
  componentDidHide() {
    console.log("detail04 componentDidHide");
  }
  onUnload() {
    console.log("detail04 onUnload");
  }
  onPullDownRefresh() {
    console.log("detail04 onPullDownRefresh");
    setTimeout(() => {
      Taro.stopPullDownRefresh();
    }, 1000);
  }
  onReachBottom() {
    console.log("detail04 onReachBottom");
  }

  render() {
    return (
      <View className="detail04">
        <View className="detail01-item">item1</View>
        <View className="detail01-item">item1</View>
        <View className="detail01-item">item1</View>
        <View className="detail01-item">item1</View>
        <View className="detail01-item">item1</View>
        <View className="detail01-item">item1</View>
        <View className="detail01-item">item1</View>
        <View className="detail01-item">item1</View>
        <View className="detail01-item">item1</View>
        <View className="detail01-item">item1</View>
        <View className="detail01-item">item1</View>
        <View className="detail01-item">item1</View>
        <View className="detail01-item">item1</View>
        <View className="detail01-item">item1</View>
        <View className="detail01-item">item1</View>
      </View>
    );
  }
}

// 13、Learn_unipaa_taro/10-pages-uni-app/pages/detail04/detail04.vue
<template>
	<view>
		<view class="item1">item1</view>
		<view class="item1">item1</view>
		<view class="item1">item1</view>
		<view class="item1">item1</view>
		<view class="item1">item1</view>
		<view class="item1">item1</view>
		<view class="item1">item1</view>
		<view class="item1">item1</view>
		<view class="item1">item1</view>
		<view class="item1">item1</view>
		<view class="item1">item1</view>
		<view class="item1">item1</view>
		<view class="item1">item1</view>
		<view class="item1">item1</view>
		<view class="item1">item1</view>
		<view class="item1">item8</view>
		<view class="item1">item9</view>
		<view class="item1">item10</view>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				msg: '我是data定义的数据'
			};
		},
		// 1.页面的生命周期
		onLoad(options) {
			console.log('detail04 onLoad');
		},
		onShow() {
			console.log('detail04 onShow');
			console.log(this);
		},
		onReady() {
			console.log('detail04 onReady');
		},
		onHide() {
			console.log('detail04 onHide');
		},
		onUnload() {
			console.log('detail04 onUnload');
		},
		onPullDownRefresh() {
			console.log('detail04 onPullDownRefresh');
			setTimeout(() => {
				// 关闭下拉刷新的图标
				uni.stopPullDownRefresh()
			}, 1000)
		},
		onReachBottom() {
			console.log('detail04 onReachBottom');
		},
		// 2.Vue组件的生命周期
		beforeCreate() {
			console.log('detail04 beforeCreate');
		},
		created() {
			console.log('detail04 created');
		},
		beforeMount() {
			console.log('detail04 beforeMount');
		},
		mounted() {
			console.log('detail04 mounted');
		},
		beforeDestroy() {
			console.log('detail04 beforeDestroy');
		},
		destroyed() {
			console.log('detail04 destroyed');
		}
	}
</script>

<style lang="scss">

.item1{
	height: 200rpx;
	border-bottom: 2rpx solid red;
}
</style>
